// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// TransactionOption is an autogenerated mock type for the TransactionOption type
type TransactionOption struct {
	mock.Mock
}

type TransactionOption_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionOption) EXPECT() *TransactionOption_Expecter {
	return &TransactionOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *TransactionOption) Execute(_a0 *sql.Tx) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type TransactionOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *sql.Tx
func (_e *TransactionOption_Expecter) Execute(_a0 interface{}) *TransactionOption_Execute_Call {
	return &TransactionOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *TransactionOption_Execute_Call) Run(run func(_a0 *sql.Tx)) *TransactionOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Tx))
	})
	return _c
}

func (_c *TransactionOption_Execute_Call) Return(_a0 error) *TransactionOption_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionOption_Execute_Call) RunAndReturn(run func(*sql.Tx) error) *TransactionOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionOption creates a new instance of TransactionOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionOption {
	mock := &TransactionOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
